somesite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from myauth.views import MyLogoutView

app_name = 'myauth'
urlpatterns = [
    path('login/', LoginView.as_view(
        template_name="myauth/login.html",
        redirect_authenticated_user=True,
    ), name="login"),

    path("logout/", MyLogoutView.as_view(), name="logout")
]

somesite/shopapp/urls.py
from django.urls import path

from .views import (
    ShopView,
    ProductsListView,
    ProductDetailViews,
    ProductDeleteView,
    OrdersList,
    OrderDetailsView,
    ProductCreateView,
    ProductUpdateView,
    OrderCreateView,
    OrderUpdateView,
)

app_name = 'shopapp'
urlpatterns = [
    path('', ShopView.as_view(), name='base'),
    path('products/', ProductsListView.as_view(), name='products'),
    path('products/details/<int:pk>/', ProductDetailViews.as_view(), name='product_details'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('orders/', OrdersList.as_view(), name='orders_list'),
    path('orders/create/', OrderCreateView.as_view(), name='order_create'),
    path('orders/update/<int:pk>/', OrderUpdateView.as_view(), name='order_update'),
    path('orders/details/<int:pk>/', OrderDetailsView.as_view(), name='order_details'),
]

somesite/somesite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('myauth/', include('myauth.urls')),
]

somesite/myauth/models.py
from django.db import models

# Create your models here.

somesite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Product(models.Model):
    FRESHMAN = 'FR'
    SOPHOMORE = 'SO'
    JUNIOR = 'JR'
    SENIOR = 'SR'
    GRADUATE = 'GR'
    YEAR_IN_SCHOOL_CHOICES = [
        (FRESHMAN, 'Freshman'),
        (SOPHOMORE, 'Sophomore'),
        (JUNIOR, 'Junior'),
        (SENIOR, 'Senior'),
        (GRADUATE, 'Graduate'),
    ]

    year_in_school = models.CharField(
        max_length=2,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default=FRESHMAN,
    )

    # def is_upperclass(self):
    #     return self.year_in_school in {self.JUNIOR, self.SENIOR}

    name = models.CharField(max_length=50, blank=False)
    description = models.TextField(max_length=200, blank=True)
    price = models.DecimalField(default=0, max_digits=5, decimal_places=2)
    create_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False, blank=False)
    test = models.TextChoices('MedalType', 'GOLD SILVER BRONZE')

    def __str__(self):
        return f'pk={self.pk}, name: {self.name!r}'


class Order(models.Model):
    delivery_address = models.TextField(max_length=100, blank=False)
    promocode = models.CharField(max_length=25, null=False, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')

    def __str__(self):
        return f'№{self.pk}, delivery address: {self.delivery_address!r}'

somesite/shopapp/forms.py
from django import forms
from django.contrib.auth.models import Group

from shopapp.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = 'name',


class GroupCreateForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = "name",

somesite/myauth/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy


def log_out_user(request: HttpRequest):
    logout(request)
    return redirect(reverse('myauth:login'))


class MyLogoutView(LogoutView):
    """
    Класс реализует выход пользователя из учётной записи
    """
    # страница, куда будет перенаправлен пользователь после разлогирования
    next_page = reverse_lazy("myauth:login")

somesite/shopapp/views.py
from django.contrib.auth.models import Group, Permission
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from shopapp.forms import ProductForm, GroupCreateForm
from shopapp.models import Product, Order


class ShopView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            'groups': Group.objects.prefetch_related('permissions').all(),
            "form": GroupCreateForm()
        }
        return render(request, 'shopapp/base.html', context=context)

    def post(self, request: HttpRequest):
        form = GroupCreateForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect(reverse("shopapp:base"))


class ProductDetailViews(DetailView):
    """
    Класс реализует детали продуктов
    """
    template_name = 'shopapp/product_details.html'
    model = Product
    context_object_name = 'product'

    # def get(self, request: HttpRequest, pk: int):
    #     product = get_object_or_404(Product, pk=pk)
    #     context = {
    #         "product": product,
    #     }
    #
    #     return render(request, "shopapp/product_details.html", context=context)


class ProductsListView(ListView):
    """
    Класс реализует список имеющихся продуктов
    """
    template_name = "shopapp/products.html"
    model = Product
    context_object_name = 'products'
    # queryset = Order.objects.prefetch_related('user')

    # def get_context_data(self, **kwargs):
    #     """
    #     Функция переопределяет/определяет значение 'products' и присваивает ему Queryset Product.
    #     """
    #     context = super().get_context_data(**kwargs)
    #     context['products'] = Product.objects.all()
    #     return context


class ProductCreateView(CreateView):
    """
    Класс реализует создание нового продукта
    """
    template_name = "shopapp/product_create.html"
    fields = 'name', 'description', 'archived'
    model = Product
    success_url = reverse_lazy("shopapp:products")


class ProductUpdateView(UpdateView):
    """
    Класс реализует обновление выбранного продукта
    """
    template_name = "shopapp/product_update.html"
    model = Product
    fields = "name", "description", "price", "archived",
    context_object_name = "product"

    def get_success_url(self):
        return reverse("shopapp:product_details", kwargs={"pk": self.object.pk})


class ProductDeleteView(DeleteView):
    """
    Класс реализует удаление выбранного продукта
    """
    template_name = "shopapp/product_delete.html"
    model = Product
    success_url = reverse_lazy("shopapp:products")
    context_object_name = "product"


class OrdersList(ListView):
    """
    Класс реализует страницу со списком заказом
    """
    template_name = "shopapp/orders_list.html"
    model = Order
    context_object_name = "orders"


class OrderDetailsView(DetailView):
    """
    Класс реализует список заказов
    """
    template_name = 'shopapp/order_details.html'
    queryset = Order.objects.prefetch_related("products").select_related("user").all()
    context_object_name = 'order'


class OrderCreateView(CreateView):
    """
    Класс реализует создание нового заказа
    """
    template_name = "shopapp/order_create.html"
    fields = "delivery_address", "user", "products",
    queryset = Order.objects.prefetch_related("products").select_related("user").all()
    success_url = reverse_lazy("shopapp:orders_list")


class OrderUpdateView(UpdateView):
    """
    Класс реализует обновление объявления
    """
    template_name = "shopapp/order_update.html"
    model = Order
    fields = "delivery_address", "user", "products",

    def get_success_url(self):
        return reverse("shopapp:order_details", kwargs={'pk': self.object.pk})

somesite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base My auth
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        <h1>Base My auth</h1>
    {% endblock %}
</body>
</html>

somesite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <h1>User login</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

somesite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Shop base
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        <h1>Base shop</h1>
        <div style="width: 15%; border: 2px black solid; padding: 15px; border-radius: 10px">
            <form method="post">
                <h2>Create new group</h2>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create Group</button>
            </form>
        </div>


        <ul>
            {% for group in groups %}
                <li>
                    <p>Group name: {{ group }}</p>
                    <p>Permissions: {{ group.permissions }}</p>
                </li>
            {% endfor %}
        </ul>


    {% endblock %}
</body>
</html>

somesite/shopapp/templates/shopapp/order_create.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order create
{% endblock %}

{% block body %}
    <h1>Order create</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create order</button>
    </form>
{% endblock %}

somesite/shopapp/templates/shopapp/order_details.html
{% extends "shopapp/base.html" %}

{% block title %}
    Order details
{% endblock %}

{% block body %}
    <h1>Order details</h1>
    <p>User: {{ order.user.username }}</p>
    <p>Order # {{ order.pk }}</p>
    <p>Delivery address: {{ order.delivery_address }}</p>
    <h3>Products:</h3>
    <ul>
        {% for product in order.products.all %}
            <li>{{ product.name }}</li>
        {% endfor %}
    </ul>

    <div>
        <a href="{% url 'shopapp:orders_list' %}">Orders list</a>
    </div>

    <div>
        <a href="{% url 'shopapp:order_update' pk=order.pk %}">Update order</a>
    </div>
{#    <div>#}
{#        <a href="{% url 'shopapp:order_update' pk=order.pk %}">Update order</a>#}
{#    </div>#}



{% endblock %}

somesite/shopapp/templates/shopapp/order_update.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order update
{% endblock %}

{% block body %}
    <h1>Order update</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update order</button>
    </form>

    <p>
        <a href="{% url 'shopapp:order_details' pk=order.pk %}">Back to orders details</a>
    </p>
{% endblock %}

somesite/shopapp/templates/shopapp/orders_list.html
{% extends "shopapp/base.html" %}

{% block title %}
    Orders
{% endblock %}

{% block body %}
    <h1>Orders</h1>
        <div>
            <a href="{% url 'shopapp:order_create' %}">Order create</a>
        </div>
    {% if orders %}
        {% for order in orders %}
            <p>Order # {{ order.pk }}</p>
            <p>Delivery address: <a href="{% url 'shopapp:order_details' pk=order.pk %}">{{ order.delivery_address }}</a> </p>

        {% endfor %}

    {% else %}
        <h3>Not orders</h3>
    {% endif %}
{% endblock %}

somesite/shopapp/templates/shopapp/product_create.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create products
{% endblock %}

{% block body %}
    <h1>Create products</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create product</button>
    </form>
{#    <p>#}
{#        <a href="{% url 'shopapp:product_details' pk=product.pk %}">Back to details {{ product.name }}</a>#}
{#    </p>#}
    <p>
        <a href="{% url 'shopapp:products' %}">Back to products list</a>
    </p>
{% endblock %}

somesite/shopapp/templates/shopapp/product_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product delete
{% endblock %}

{% block body %}
    <h1>Are you sure you wont delete {{ product.name|capfirst }} </h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Product delete</button>
    </form>

    <p>
        <a href="{% url 'shopapp:product_details' pk=product.pk %}">Back to product details</a>
    </p>
{% endblock %}

somesite/shopapp/templates/shopapp/product_details.html
{% extends "shopapp/base.html" %}


{% block title %}
    Products detail
{% endblock %}

{% block body %}
    <h1>Product detail</h1>

    <div>
        <p>Product name: {{ product.name }}</p>
        <p>Product description: {% firstof product.description 'No description' %}</p>
        <p>Product price: {{ product.price }}</p>
    </div>

    <div>
        <a href="{% url 'shopapp:product_update' pk=product.pk %}">Product update</a>
    </div>
    <div>
        <a href="{% url 'shopapp:product_delete' pk=product.pk %}">Product delete</a>
    </div>

    <div>
        <a href="{% url 'shopapp:products' %}">Back to product list</a>
    </div>
{% endblock %}

somesite/shopapp/templates/shopapp/product_update.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product update
{% endblock %}

{% block body %}
    <h1>Product update</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update product</button>
    </form>

    <p>
        <a href="{% url 'shopapp:product_details' pk=product.pk %}">Back to product details</a>
    </p>
{% endblock %}

somesite/shopapp/templates/shopapp/products.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Products
{% endblock %}

{% block body %}
    <h1>Products list</h1>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">Orders list</a>
    </div>

    {% if products %}
        <ul>
            {% for product in products %}
                <li>product name: <a href="{% url 'shopapp:product_details' pk=product.pk %}">{{ product.name }}</a>  </li>
                <li>product description: {% firstof product.description 'No description' %}</li>
                <li>product price: {{ product.price }}</li>
                <hr>
            {% endfor %}
        </ul>


    {% else %}
        NO Products
    {% endif %}

{% endblock %}