mysite/myauth/urls.py
from django.urls import path
from .views import (
    auth_base,
    MyLoginView,
    MyLogoutView,
    RegisterView,
    AboutMeView,
    get_cookie_view,
    set_cookie_view,
    get_session_view,
    set_session_view,
    UserListView,
    UserDetailsView,
)

app_name = 'myauth'
urlpatterns = [
    path('', auth_base, name='base'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('users/', UserListView.as_view(), name='users_list'),
    path('user-details/<int:pk>/<str:name>', UserDetailsView.as_view(), name='user_details'),
    path('cookie/get', get_cookie_view, name='cookie-get'),
    path('cookie/set', set_cookie_view, name='cookie-set'),
    path('session/get', get_session_view, name='session-get'),
    path('session/set', set_session_view, name='session-set'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView
)
from django.contrib.sitemaps.views import sitemap

from .sitemaps import sitemaps

urlpatterns = [
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns += i18n_patterns(
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('req/', include('requestdataapp.urls')),
    path('accounts/', include('myauth.urls')),
    path('blog/', include('BlogApp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

mysite/shopapp/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include


from shopapp.api import ProductViewSet, OrderViewSet
from .views import (
    shop_index,
    groups_list,
    ProductListView,
    ProductDetailsView,
    ProductUpdateView,
    ProductCreateView,
    ProductDeleteView,
    OrderListView,
    OrderCreateView,
    OrderDetailsView,
    OrderUpdateView,
    OrderDeleteView,
    OrdersDataExportView,
    LatestProductsFeed,
    UserOrdersListView,
    user_orders_export_data,
)

routers_product = DefaultRouter()
routers_product.register('products', ProductViewSet)

routers_order = DefaultRouter()
routers_order.register('orders', OrderViewSet)

app_name = 'shopapp'
urlpatterns = [ 
    path('', shop_index, name='index'),
    path('api/products/', include(routers_product.urls)),
    path('api/orders/', include(routers_order.urls)),
    path('groups/', groups_list, name='groups_list'),
    path('products/<str:name>/', ProductListView.as_view(), name='products_list'),
    path('products/create/<str:name>', ProductCreateView.as_view(), name='product_create'),
    path('products/<str:name>/<int:pk>/', ProductDetailsView.as_view(), name='product_details'),
    path('products/<str:name>/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<str:name>/<int:pk>/archive/', ProductDeleteView.as_view(), name='product_archive'),
    path('orders/', OrderListView.as_view(), name='orders_list'),
    path('orders/create', OrderCreateView.as_view(), name='order_create'),
    path('orders/export/', OrdersDataExportView.as_view(), name='orders_export'),
    path('orders/<int:pk>/', OrderDetailsView.as_view(), name='order_details'),
    path('orders/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
    path('products/latest/feed/', LatestProductsFeed(), name='products_feed'),
    path('users/<int:user_id>/orders/', UserOrdersListView.as_view(), name='user_orders'),
    path('users/<int:user_id>/orders/export/', user_orders_export_data, name='user_orders_export'),
]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Product(models.Model):
    """
    Класс Product создаёт таблицу в db
    """
    class Meta:
        ordering = ['pk', 'name', ]
        verbose_name = _('Product')
        verbose_name_plural = _('Product')

    def __str__(self):
        return f'Product № {self.pk}, product name: {self.name!r}'

    name = models.CharField(max_length=100, blank=False)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=5, decimal_places=2, blank=False)
    discount = models.DecimalField(default=0, max_digits=5, decimal_places=2)
    count = models.PositiveSmallIntegerField(default=0)
    create_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def get_absolute_url(self):
        """
        Функция возвращает ссылку на продукт при её запросе
        """
        return reverse('shopapp:product_details', kwargs={'pk': self.pk, 'name': self.name})


class Order(models.Model):
    class Meta:
        ordering = ['pk', ]  # Sort by name,  ['-name'], or ['name', 'price']
        # db_table = ''
        verbose_name = _('Orders')
        verbose_name_plural = _('Orders')

    delivery_address = models.TextField(blank=True)
    promo_code = models.CharField(blank=True, max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')

    def __str__(self) -> str:
        return f'Order №{self.pk}, delivery address={self.delivery_address!r}'

mysite/shopapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelChoiceField


class JSONImportForm(forms.Form):
    json_file = forms.FileField()

mysite/shopapp/views.py
import logging

from timeit import default_timer

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import Group, User
from django.contrib.syndication.views import Feed
from django.core.cache import cache
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from .models import Product, Order

log = logging.getLogger(__name__)


def shop_index(request: HttpRequest) -> HttpResponse:
    products = [
        ('laptop', 2569),
        ('desktop', 75000),
        ('smart', 7000),
        ('pop', 3719),
        ('jawa', 71)

    ]
    context = {
        'time_running': default_timer(),
        'products': products,
        'all_products': Product.objects.all(),
    }
    return render(request=request, template_name='shopapp/shop-index.html', context=context)


def groups_list(request: HttpRequest) -> HttpResponse:
    context = {
        'groups': Group.objects.prefetch_related('permissions').all(),
    }
    return render(request=request, template_name='shopapp/group-list.html', context=context)


class ProductListView(ListView):
    model = Product


class ProductDetailsView(DetailView):
    model = Product


class ProductCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'add_product',
    model = Product
    fields = 'name', 'price', 'description', 'discount', 'count', 'archived'
    success_url = reverse_lazy('shopapp:products_list')

    def get_success_url(self):
        return reverse(
            'shopapp:products_list', kwargs={'name': self.request.user}
        )

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        if self.request.user.is_superuser or \
                Product.objects.all().filter(created_by_id=self.request.user).filter(name=self.get_object().name):
            return True
        return False

    model = Product
    fields = 'name', 'price', 'description', 'discount', 'count', 'archived'
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            'shopapp:product_details', kwargs={'pk': self.object.pk, 'name': self.request.user}
        )


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'delete_product',
    model = Product

    # success_url = reverse_lazy('shopapp:products_list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)

    def get_success_url(self):
        return reverse(
            'shopapp:products_list', kwargs={'name': self.request.user}
        )


class OrderListView(LoginRequiredMixin, ListView):
    model = Order


class OrderCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'add_product',
    model = Order
    fields = 'delivery_address', 'promo_code', 'user', 'products'
    success_url = reverse_lazy('shopapp:orders_list')


class OrderDetailsView(DetailView):
    model = Order


class OrderUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'change_product',
    model = Order
    fields = 'user', 'products'
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse('shopapp:order_details', kwargs={'pk': self.object.pk})


class OrderDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'delete_product',
    model = Order
    success_url = reverse_lazy('shopapp:orders_list')


class OrdersDataExportView(UserPassesTestMixin, View):
    """
    Класс реализует экспорт данных в файл в json формате
    """
    def test_func(self):
        return self.request.user.is_staff

    def get(self, request: HttpRequest) -> JsonResponse:
        orders = Order.objects.order_by('pk').select_related('user').prefetch_related('products').all()
        order_data = [
            {
                'pk': order.pk,
                'delivery_address': order.delivery_address,
                'promo_code': order.promo_code,
                # 'created_at': order.created_at,
                'user': order.user.username,
                'products': [product.id for product in order.products.all()],
            }
            for order in orders]
        return JsonResponse({'order': order_data})


class LatestProductsFeed(Feed):
    """
    Класс отдаёт данные RSS каналам.
    """
    title = 'Магазин продуктов'  # текст будет отображаться над статьёй
    description = 'Новые продукты'
    link = reverse_lazy('shopapp:products_list', kwargs={'name': 'Lol'})

    def items(self):
        """
        Возвращает список продуктов, можно фильтровать, сортировать
        """
        return Product.objects.filter(archived=False).order_by('-create_at')[:3]

    def item_title(self, item: Product):  # возвращает заголовок статьи в ленту
        return item.name

    def item_description(self, item: Product):  # возвращает описание товара с ограничением по символам
        if item.description:
            return item.description[:100]
        return 'No description'


class UserOrdersListView(UserPassesTestMixin, ListView):
    """
    Клас принимает на вход id пользователя и возвращает список заказов пользователя
    """

    def test_func(self):
        """
        Функция относится к классу UserPassesTestMixin и реализует проверку, если возвращается True,
        тогда класс UserOrdersListView будет работать
        """
        return self.request.user.is_staff or (self.request.user.is_authenticated and
                                              self.kwargs['user_id'] == self.request.user.id)

    template_name = 'shopapp/user_orders.html'  # путь к шаблону
    context_object_name = 'user_orders'  # имя, по которому будет доступ к данным внутри шаблона

    def get_queryset(self, **kwargs):
        """
        Функция определяет данные, которые будет принимать класс UserOrdersListView
        и которыми можно оперировать в шаблоне
        """
        owner = get_object_or_404(User, pk=self.kwargs['user_id'])  # получаем объект пользователя
        orders = Order.objects.filter(user=owner).all()  # получаем заказы отфильтрованные по пользователю
        context = {
            'user': owner,
            'orders': orders,
        }
        return context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


def user_orders_export_data(request: HttpRequest, user_id: int):
    """
    Функция принимает id пользователя, получает пользователя и его заказы, далее формирует словарь
    с заказами пользователя и отправляет его в json формате, если ранее данные подгружались,
    в этом случае они берутся из кэша
    """

    cache_key = f'user_orders_{user_id}'  # индивидуальный ключ кэша для каждого пользователя
    context = cache.get(cache_key)  # проверка наличия ключа в кэше
    if context is None:  # если ключа в кэше не найден
        user = get_object_or_404(User, pk=user_id)  # получаем из базы пользователя по id
        orders = Order.objects.filter(user=user).all().order_by('-pk')  # получаем из базы список заказа пользователя
        context = [
            {
                'user': user.username,
                'orders': [
                    {
                     'pk': order.pk,
                     'delivery_address': order.delivery_address,
                     'products': [product.id for product in order.products.all()],
                    }
                    for order in orders]
            }
        ]
        cache.set(cache_key, context, 60 * 2)  # создаём кэш с указанием ключа и временем существования
    return JsonResponse({'orders': context})

mysite/shopapp/templates/shopapp/base.html
{% load i18n %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base title
        {% endblock %}
    </title>
    <style>
        .field{color:green;}
        .error{color:red;}
        .p{margin: 0;}
        .vis{visibility: hidden; height: 0}
    </style>
</head>
<body>
    {% block body %}
        Base Body
    {% endblock %}

    <div>
        {% now 'H:i' %}
    </div>

    <div>
        {% now 'l' as currennt_weekday %}
        {% translate 'Current week day' %}: {{ currennt_weekday }}
    </div>
</body>
</html>

mysite/shopapp/templates/shopapp/group-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Groups List
{% endblock %}

{% block body %}
    <h1>Groups</h1>
    <div>
        {% if not groups %}
            <h3>Not groups</h3>
        {% else %}
            {% for group in groups %}
                <ul>
                    <li>
                        <div>{{ group.name }}</div>
                        <ul>
                            {% for permissions in group.permissions.all %}
                                <li>{{ permissions.name }}</li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order delete
{% endblock %}

{% block body %}
    <h1>A you sure you want to delete order #{{ object.pk }} ?</h1>
    <br>
    <div>
        <form action="#" method="post">
            {% csrf_token %}
            <div class="vis">
                {{ form.as_p }}
            </div>
            <button type="submit">Delete</button>
        </form>
    </div>
    <br>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order details</a>
    </div>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">Orders list</a>
    </div>
    <br>
{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order details
{% endblock %}

{% block body %}
    <h1>Details order #{{ object.pk }}</h1>
    <p><strong>Customer:</strong> {% firstof object.user.username object.user.first_name %}</p>
    <p><strong>Delivery address:</strong> {{ object.delivery_address }}</p>
    <p><strong>Promo_code:</strong> {{ object.promo_code }}</p>
    <p><strong>Created_at:</strong> {{ object.created_at }}</p>
    <ul>
        <div><strong>Products order:</strong></div>
        {% for name_product in object.products.all %}
            <li>{{ name_product.name }}</li>
        {% endfor %}
    </ul>
    <p>
        <a href="{% url 'shopapp:orders_list' %}">Orders list</a>
    </p>
    <p>
        <a href="{% url 'shopapp:order_update' pk=object.pk %}">Order update</a>
    </p>
    <p>
        <a href="{% url 'shopapp:order_delete' pk=object.pk %}">Order delete</a>
    </p>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order List
{% endblock %}

{% block body %}
    <h1>Orders list</h1>
    <p>
        <a href="{% url 'shopapp:products_list' name=user.username %}">Products list</a>
    </p>
    <p>
        <a href="{% url 'shopapp:order_create' %}">Order create</a>
    </p>

    {% if object_list %}
        {% for order in object_list %}
            <p class="p">
                <a href="{% url 'shopapp:order_details' pk=order.pk %}">
                    <strong>Order #</strong>{{ order.pk }}
                </a>
            </p>
            <p class="p"><strong>Order by:</strong> {% firstof order.user.first_name order.user.username %}</p>
            <br>
            <div>
                <strong>Product in order:</strong>
            </div>
            <ul class="p">
                {% for product in order.products.all %}
                    <li>{{ product.name }} for ${{ product.price }} </li>
                {% endfor %}
            </ul>
            <br>
            <div>______________________________</div>
            <br>
        {% endfor %}

    {% else %}
        <h3>No orders</h3>
    {% endif %}

{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Update order #{{ object.pk }}</h1>

    <form action="#" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <p>
            <button type="submit">Update</button>
        </p>
    </form>
    <br>
    <p>
        <a href="{% url 'shopapp:orders_list' %}">Orders list</a>
    </p>
    <p>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">Back to order details</a>
    </p>

{% endblock %}

mysite/shopapp/templates/shopapp/orders_changelist.html
{% extends "admin/change_list.html" %}

{% block object-tools-items %}
    {% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_orders_json' %}" class="addlink">
            Import JSON
        </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product archive
{% endblock %}

{% block body %}
    <h1>A you sure you want to archive "{{ product.name }}" ?</h1>
    <br>
    <br>
    <div>
        <form action="#" method="post">
            {% csrf_token %}
            <div class="vis">
                {{ form.as_p }}
            </div>

            <button type="submit">Archive</button>
        </form>
    </div>
    <br>

    <div>
        <a href="{% url 'shopapp:product_details' pk=product.pk name=user.username %}">Back to product</a>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' name=user.username %}">Product list</a>
    </div>
    <br>
{% endblock %}

mysite/shopapp/templates/shopapp/product_detail.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Prod' %}: {{ object.name }}
{% endblock %}

{% block body %}
    <h1>{% translate 'Detail product' %}: {{ object.name }}</h1>
    <div>

        <p>
            <strong>{% translate 'Price' context 'price product' %}:</strong> {{ object.price }}
            {% blocktranslate count price=product.price %}
                ruble
                {% plural %}
                rubles
            {% endblocktranslate %}
        </p>
        <p>
            {% blocktranslate count product_count=object.count %}
                <strong>Count:</strong> {{ product_count }} product
                {% plural %}
                <strong>Count:</strong> {{ product_count }} products
            {% endblocktranslate %}
        </p>
        <p><strong>{% translate 'Description' context 'description product' %}:</strong> {{ object.description }}</p>
        <p>
            {% blocktranslate count product_discount=product.discount %}
                <strong>The discount is:</strong> {{ product_discount }} percent
                {% plural %}
                <strong>Product discount:</strong> {{ product_discount }} percent
            {% endblocktranslate %}
        </p>
        <p><strong>{% translate 'Archived' context 'archived product' %}:</strong> {{ object.archived }}</p>
        <p><strong>{% translate 'Create' context 'create product' %}:</strong> {{ object.create_at }}</p>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' name=user.username %}">
            {% translate 'Products list' context 'link' %}</a>
    </div>
    <div>
        <a href="{% url 'shopapp:product_update' pk=object.pk name=user.username %}">
            {% translate 'Product update' context 'link' %}</a>
    </div>
    <div>
        <a href="{% url 'shopapp:product_archive' pk=object.pk name=user.username %}">
            {% translate 'Product archive' context 'link' %}</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Form create product
{% endblock %}

{% block body %}
    <h1>Form create product</h1>
    <form action="#" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p>
            <button type="submit">Create</button>
        </p>
    </form>
    <div>
        <a href="{% url 'shopapp:products_list' name=user.username %}">Product list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Products list
{% endblock %}

{% block body %}

    <h1>Products list</h1>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">Orders list</a>
    </div>
    {% if perms.foo.add_product %}
        <div>
            <a href="{% url 'shopapp:product_create' name=user.username %}">Create products</a>
        </div>
    {% endif %}

    <br>
    {% if object_list %}
        <div>
        {% for product in object_list %}
            {% if  product.archived == False %}
                <p>
                    <a href="{% url 'shopapp:product_details' pk=product.pk name=user.username %}">
                        <strong>Name:</strong> {{ product.name }}
                    </a>
                </p>
                <p><strong>Price product:</strong> {{ product.price }}</p>
                <p><strong>Discount:</strong> {% firstof product.discount 'No discount' %} </p>
                ________________________
            {% endif %}
        {% endfor %}
        </div>
    {% else %}
        <div>No products</div>
    {% endif %}

{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Shop Index
{% endblock %}

{% block body %}
    <h1>
        Hello Shop Index
    </h1>

    <ul>
        {% for name, price in products %}
            <li>{{ name }} {{ name|length }} for ${{ price }}</li>
            {% if  name|length_is:'4' %}
                <span>Lucky product</span>
            {% endif %}
            <div>Добавим к слову: 2 было {{ name }}, стало {{ name|add:'2' }}</div>
            <div>Напишем слово с большой буквы: было {{ name }}, стало {{ name|capfirst }}</div>
            <div>Напишем слово большими буквами: было {{ name }}, стало {{ name|upper }}</div>
            <div>Удалим из слова символы: a было {{ name }}, стало {{ name|cut:'a' }}</div>
        {% empty %}
            No products
        {% endfor %}
    </ul>

    <div>
        {% lorem 2 p random %}
    </div>

    <p>
        <a href="{% url 'shopapp:products_list' name=user.username %}">Products list</a>
    </p>
{% endblock %}

mysite/shopapp/templates/shopapp/user_orders.html
{% extends 'shopapp/base.html' %}
{% load cache %}


{% block title %}
    User orders
{% endblock %}

{% block body %}
    {% if user.is_authenticated %}
        <h1>User orders</h1>
        <h2>User: {{ object_list.user.username|capfirst }}</h2>
        {% cache 6 user_orders object_list.user.id %}
            {% if user_orders.orders %}
                {% for order in user_orders.orders %}
                    <h3>Order # {{ order.pk }}</h3>
                    {% if order.products.all %}
                        <ol>
                            {% for product in order.products.all %}
                                <li>{{ product.name }}</li>
                            {% endfor %}
                        </ol>
                        {% if not forloop.last %}
                            <hr>
                        {% endif %} 

                    {% else %}
                        <p style="margin-left: 25px">No orders</p>
                        {% if not forloop.last %}
                            <hr>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            {% else %}
                <h3>User has no orders</h3>
            {% endif %}
        {% endcache %}
    {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/user_orders_export.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Export of user orders
{% endblock %}

{% block body %}
    <h1>Export of user orders</h1>
{% endblock %}