mysite/myauth/urls.py
from django.urls import path
from .views import (
    auth_base,
    MyLoginView,
    MyLogoutView,
    RegisterView,
    AboutMeView,
    get_cookie_view,
    set_cookie_view,
    get_session_view,
    set_session_view,
    UserListView,
    UserDetailsView,
)

app_name = 'myauth'
urlpatterns = [
    path('', auth_base, name='base'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('users/', UserListView.as_view(), name='users_list'),
    path('user-details/<int:pk>/<str:name>', UserDetailsView.as_view(), name='user_details'),
    path('cookie/get', get_cookie_view, name='cookie-get'),
    path('cookie/set', set_cookie_view, name='cookie-set'),
    path('session/get', get_session_view, name='session-get'),
    path('session/set', set_session_view, name='session-set'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView
)
from django.contrib.sitemaps.views import sitemap

from .sitemaps import sitemaps

urlpatterns = [
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns += i18n_patterns(
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('req/', include('requestdataapp.urls')),
    path('accounts/', include('myauth.urls')),
    path('blog/', include('BlogApp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def avatar_user_directory_path(instance: 'Profile', filename: str) -> str:
    return f'profiles/user_{instance.user.pk}/avatar/{filename}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=avatar_user_directory_path)

mysite/myauth/forms.py
from django import forms

from myauth.models import Profile


class UserCreationForm(forms.ModelForm):
    class Meta:
        permissions = (('change_profile', ),)

mysite/myauth/views.py
import logging

from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponse
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DetailView

from myauth.models import Profile

log = logging.getLogger(__name__)


def auth_base(request: HttpRequest) -> HttpResponse:
    context = {}
    return render(request=request, template_name='myauth/base.html', context=context)


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'myauth/register.html'

    def get_success_url(self):
        return reverse('myauth:login')

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password2')
        user = authenticate(self.request, username=username, password=password)
        login(request=self.request, user=user)
        return response


class AboutMeView(UserPassesTestMixin, UpdateView):
    template_name = 'myauth/about-me.html'
    model = Profile
    fields = 'avatar',
    success_url = reverse_lazy('myauth:about-me')

    def test_func(self):
        return self.request.user.has_perm('myauth.change_profile')

    def get_object(self, queryset=None):
        return self.request.user.profile


class UserListView(UserPassesTestMixin, ListView):
    template_name = 'myauth/users-list.html'
    model = Profile
    # queryset = (Profile.objects.select_related('user').all())

    def test_func(self):
        log.info('User list')
        return self.request.user.is_staff


class UserDetailsView(UserPassesTestMixin, UpdateView):
    template_name = 'myauth/user-details.html'
    model = Profile
    # queryset = (Profile.objects.select_related('user').all())
    fields = 'avatar',

    def test_func(self):
        log.info('User details view')
        if self.request.user.is_staff:
            return True
        self.object = self.get_object()
        if self.request.user.pk == self.object.user.pk:
            return True
        return False

    def get_success_url(self):
        return reverse('myauth:user_details', kwargs={
            'pk': self.object.pk,
            'name': self.object.user.username
        })


class MyLoginView(LoginView):
    template_name = 'myauth/login.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse('myauth:about-me')


class MyLogoutView(LogoutView):
    redirect_field_name = 'myauth/login.html'
    extra_context = {'title': 'Goodbye'}


def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse('Cookie set')
    response.set_cookie('fizz', 'buzz', max_age=3600)
    return response


def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get('fizz', 'default value')
    return HttpResponse(f'Cookie value: {value!r}')


def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session['foobar'] = 'spameggs'
    return HttpResponse('Session set!')


def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get('foobar', 'default')
    return HttpResponse(f'Session value: {value!r}')

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}

{% block title %}
    User info
{% endblock %}

{% block body %}
    <h1>About me</h1>
    {% if user.is_authenticated %}
        <p>Name: {% firstof object.user.firstname object.user.username %} </p>
        <p>Last name: {% firstof object.user.last_name 'No' %}</p>
        <p>Email: {% firstof object.user.email 'No' %}</p>
        <p>BIO: {% firstof object.bio 'No' %}</p>
        <div>
            <h3>User avatar:</h3>
            {% if object.avatar %}
                <img src="{{ object.avatar.url }}" alt="Avatar user {{ object.user.username }}">
            {% else %}
                <strong>Image not added</strong>
            {% endif %}
        </div>

        {% if request.user.pk == object.user.pk %}
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update avatar</button>
            </form>
        {% endif %}
        {% if user.is_staff %}
            <div>
                <a href="{% url 'myauth:users_list' %}">To users list</a>
            </div>
        {% endif %}
    {% endif %}

{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Auth Base
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        <h1>Auth base</h1>
    {% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <h1>Login</h1>
    <div>
        <form action="#" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p>
                <button type="submit">Login</button>
            </p>
        </form>
    </div>
{% endblock %}

mysite/myauth/templates/myauth/profile_update_form.html
{% extends 'myauth/base.html' %}

{% block title %}
    Update profile
{% endblock %}

{% block body %}
    {% if request.user.pk == object.user.pk or request.user.is_staff and user.is_authenticated %}
       <h1>
            Update profile {% firstof object.user.lastname object.user.username %}
        </h1>
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update profile</button>
        </form>

        <h3>Current avatar:</h3>

        {% if object.avatar %}
            <div>
                <img src="{{ object.avatar.url }}" alt="">
            </div>
        {% else %}
            No avatar
        {% endif %}
        <div>
            <a href="{% url 'myauth:about-me' pk=object.pk name=object.user.username %}">
                Go to details user {{ object.user.username }}
            </a>
        </div>

    {% else %}
        <h2>You are not authorized to view this page</h2>
    {% endif %}

{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
    Register user
{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form action="#" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p>
            <button type="submit">Register</button>
        </p>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/user-details.html
{% extends 'myauth/base.html' %}

{% block title %}
    User details
{% endblock %}

{% block body %}
    <h1>User details</h1>
    <div>
        <p>
            <strong>Name:</strong> {% firstof object.user.first_name object.user.username %}
        </p>
        <p>
            <strong>Last name:</strong> {% firstof object.user.last_name 'No' %}
        </p>
        <p>
            <strong>Email:</strong> {% firstof object.user.email 'No' %}
        </p>
        <div>
            <div>
                <strong>Avatar:</strong>
            </div>
            {% if object.avatar %}
                <img src="{{ object.avatar.url }}"
                     alt="Avatar user {% firstof object.user.first_name object.user.username %}">
            {% else %}
                <p>No avatar</p>
            {% endif %}
        </div>
        {% if user.is_staff or request.user.pk == object.user.pk %}
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update avatar</button>
            </form>
        {% endif %}
        <br>
        {% if user.is_staff %}
            <a href="{% url 'myauth:users_list' %}">To users list</a>
        {% endif %}

    </div>
{% endblock %}

mysite/myauth/templates/myauth/users-list.html
{% extends 'myauth/base.html' %}

{% block title %}
    Users list
{% endblock %}

{% block body %}
    <h3>Users list</h3>
    {% if user.is_staff %}
        {% if object_list %}
            {% for object in object_list %}
                    <div>
                        <a href="{% url 'myauth:user_details' pk=object.pk name=object.user.username %}">
                            Information about the user {{ object.user.username }}
                        </a>
                    </div>
                <br>
            {% endfor %}
        {% else %}
            <div>No users</div>
        {% endif %}
    {% else %}
        <h3>You are not authorized to view this page, please login as administrator</h3>
    {% endif %}
{% endblock %}